# Generated by Django 3.2 on 2021-04-15 06:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=254)),
                ('source', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('surface_ty', models.CharField(max_length=254)),
                ('smoothness', models.CharField(max_length=254)),
                ('one_way', models.IntegerField()),
                ('osm_class', models.CharField(max_length=254)),
                ('road_class', models.CharField(max_length=254)),
                ('global_id', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'road',
            },
        ),
    ]
