# Generated by Django 3.2 on 2021-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='road',
            options={},
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
