# Generated by Django 3.2 on 2021-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0002_auto_20210415_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='road',
            name='smoothness',
            field=models.CharField(max_length=254, null='False'),
        ),
    ]
