# Generated by Django 3.2 on 2021-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0003_auto_20210415_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=254, null='False'),
        ),
    ]
