# Generated by Django 3.2 on 2021-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0004_alter_road_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='surface_ty',
            field=models.CharField(max_length=254, null='False'),
        ),
    ]
