# Generated by Django 3.2 on 2021-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0006_alter_road_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='source',
            field=models.CharField(max_length=254, null='False'),
        ),
    ]
