# Generated by Django 3.2 on 2021-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0007_alter_road_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='global_id',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='road',
            name='osm_class',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_class',
            field=models.CharField(max_length=254, null='False'),
        ),
    ]
