# Generated by Django 3.2 on 2021-04-16 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0008_auto_20210415_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('state_code', models.CharField(max_length=254)),
                ('source', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('alt_name', models.CharField(max_length=254)),
                ('ward_code', models.CharField(max_length=254)),
                ('is_primary', models.IntegerField()),
                ('global_id', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
