# Generated by Django 3.2 on 2021-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0009_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='alt_name',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='places',
            name='global_id',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='places',
            name='source',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='places',
            name='state_code',
            field=models.CharField(max_length=254, null='False'),
        ),
        migrations.AlterField(
            model_name='places',
            name='ward_code',
            field=models.CharField(max_length=254, null='False'),
        ),
    ]
