# Generated by Django 3.2 on 2021-04-16 16:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk', '0010_auto_20210416_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='boundary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
